### ISSUE TITLE
Checkoff list for todo cmd

### ISSUE THREAD

**Issue by chrisngyn** [chrisngyn/Rosie#7]
- [x] abstract cmds to separate functions in switch case
- [ ] when you run a query even if it does nothing it'll print a success statement in the discord even if it didn't do jack in the DB
- [ ] when you want to del something / mark as cmpl, you have to type the FULL STRING. there has to be a better way

**Comment by chrisngyn** [comment]
Closed by #9.
